/*
 * Producer
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Employee;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for ProducerControllerApi
 */
@Ignore
public class ProducerControllerApiTest {

    private final ProducerControllerApi api = new ProducerControllerApi();

    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteEmployeeRecTest() throws Exception {
        String email = null;
        String response = api.deleteEmployeeRec(email);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void displayAllTest() throws Exception {
        List<Employee> response = api.displayAll();

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void enrollNewEmployeeTest() throws Exception {
        Employee body = null;
        String response = api.enrollNewEmployee(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getSpecificEmployeeRecTest() throws Exception {
        String email = null;
        Employee response = api.getSpecificEmployeeRec(email);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateSpecificEmployeeRecTest() throws Exception {
        Employee body = null;
        String response = api.updateSpecificEmployeeRec(body);

        // TODO: test validations
    }
}
